### ISSUE TITLE
Test mat file

### ISSUE THREAD

**Issue by giwoncho** [ramintoosi/ROSS#13]
Hello,

I’ve tried running the Python code multiple times, but I kept encountering issues. After some troubleshooting, I realized that the problem was due to my Apple Silicon chip. I then tried running the code on a computer cluster with Linux, but it didn’t work due to the lack of graphics support.

I decided to switch back to the MATLAB version, but I’ve encountered several errors. The main issue is that my .nev file won’t load into the MATLAB code. To work around this, I attempted to use the NPMK (https://github.com/BlackrockNeurotech/NPMK/tree/v5.5.5.0) code to convert the .nev file to a .mat file for use in your code. However, this approach also didn’t work.

I suspect it might be a compatibility issue, or perhaps the .mat file I generated isn’t compatible with your code. Could you please share a test .mat file for reference? The video description you provided seems to differ from my experience. When I loaded my converted .mat file, it only showed the RawData option, and I couldn’t access LFP or Spike options.

Thank you for your help!

**Comment by ramintoosi** [comment]
Hi, 

We are thrilled to see researchers worldwide using ROSS for their work! However, the ROSS toolbox does not natively support various file types—it would be challenging to accommodate them all. Therefore, the user needs to convert their data into a `.mat` file format. This decision has allowed us to focus on improving other aspects of the toolbox to make it more user-friendly for researchers.

Regarding your issue on macOS, please refer to issue #11 ([this comment](https://github.com/ramintoosi/ROSS/issues/11#issuecomment-2513591017)) to see if the proposed solution resolves your problem.

As for the `.mat` files, the names of the variables inside the file are not important. However, the dimension of the variable you select to load is critical. It must have dimensions of `nx1`. To assist you, I’ve attached a [test zip file](https://github.com/user-attachments/files/17988114/ross_test.zip) that contains `.mat` file  to this comment that loads correctly in the code (load the .mat file not the zip file. I uploaded a zip since the GitHub does not allow to attach a .mat file). When you load it, you will see a variable named `test`, which can be loaded without issues. 

Note that this file only contains 1000 samples (to keep the file size small), so you likely won’t be able to proceed with detection or sorting. However, by loading it into MATLAB, you can examine the structure and shape of the variable inside it as a reference.

[ross_test.zip](https://github.com/user-attachments/files/17988114/ross_test.zip)

**Comment by giwoncho** [comment]
Hi,

Thank you so much for providing the test mat file. I was able to test it and confirm the correct type of MATLAB file after inspecting it. The issue was that my data type was not set to single or double (it was int or unit). Once I changed the data type, everything worked well. So far, I’ve been able to detect the signal and plot the histogram. However, when I tried to perform automatic sorting, I encountered the following message:

<img width="299" alt="image" src="https://github.com/user-attachments/assets/d44d2466-b993-4428-945c-a037f6d440c5">

Can you also help me to figure out how to solve this?

Thanks
Giwon

**Comment by giwoncho** [comment]
<img width="300" alt="image" src="https://github.com/user-attachments/assets/80de0920-94c6-43fc-bdd1-29b892eecd6a">
I also attached my log. It might be my data issue I think. My samples are only 1M which looks very less. I also attached histogram. 
<img width="308" alt="image" src="https://github.com/user-attachments/assets/7ee02335-1c5b-4c3a-b7b2-9902b55373ae">

Still It would be better to understand why it is not working so that I can make a dataset properly again.

**Comment by giwoncho** [comment]
Hi,

I noticed that my waveform file has the format 48 X 1006999, which isn’t loading because it’s not in a 1 X N or N X 1 format. Do you recommend converting the data to a 1 X N format? If so, could you advise on the appropriate data structure?

GIwon

**Comment by giwoncho** [comment]
I solved the issue by reshaping matrix into 1XN format. Thanks!

**Comment by ramintoosi** [comment]
Thank you for sharing your issues and the approach you used to address them. Since we do not currently support multi-channel spike sorting, alternative methods such as flattening the multi-channel data need to be employed as a workaround. We appreciate you sharing your insights.
