### ISSUE TITLE
Auto-sorting does not function with alignment checked

### ISSUE THREAD

**Issue by jjsakon** [ramintoosi/ROSS#4]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/29741844/204421530-c318c4f4-4bc4-40e3-a8f4-d74a30ebdc96.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/29741844/204421586-e4d9552e-b8e7-4b47-926a-ff5f3190348c.png">

It works without Alignment and Statistical Filtering checked, but I don't even know how to interpret the clusters without alignment.

**Comment by ramintoosi** [comment]
There always exists a standard alignment that aligns waveforms based on the minimum point of the waveforms. The alignment option in auto-sorting is for the multi-point alignment introduced in our [paper](https://www.nature.com/articles/s41598-021-93088-w). Parameters of multi-point alignment and statistical filtering need to be modified based on your data. You probably need to modify them for one session with try and error and use that for the rest of your data. Check the interpretation of the parameters in our [documentation](https://github.com/ramintoosi/ROSS/blob/master/documentation.pdf).
BTW, since we have not seen this error in our lab, if you send me a sample of your data, I can check and resolve the error to improve ROSS.
